### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#13]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-card--default

- [x] Remove **eea-card** class, style default card 
- [x] Remove overrides for things that are found within **card.less**
  https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/views/card.less#L29
- [x] Remove overly specific html tag selectors, use only **.ui.card** as fragment that needs changing
  https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/views/card.overrides#L5
- [ ] Remove border-radius on the first child (the image). The card has sharp corners, while the image used in the card has border-radius and makes empty corner appear. I think this is due to the fact that cards were initially designed with round corners and later all boxes redesigned to have sharp corners.

**Comment by ichim-david** [comment]
- [  ] Remove **eea-card** class, style default card 
- [  ] Remove overrides for things that are found within **card.less**
  https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/views/card.less#L29
- [  ] Remove overly specific html tag selectors, use only **.ui.card** as fragment that needs changing
  https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/views/card.overrides#L5

**Comment by demarant** [comment]
- [ ] Remove border-radius on the first child (the image). The card has sharp corners, while the image used in the card has border-radius and makes empty corner appear. I think this is due to the fact that cards were initially designed with round corners and later all boxes redesigned to have sharp corners.

**Comment by ichim-david** [comment]
@g-stamatis I've checked the latest round of changes to the card and I have the following comments

I like that you've removed the overrides and you made use of the variables
https://github.com/eea/volto-eea-design-system/blob/develop-itml/src/customizations/components/theme/Card/Card.stories.js
https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/views/card.variables
https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/views/card.overrides

The only thing that you need to do is to have a few more examples in the storybooks when you have items of different width in text and images as that will perhaps make you introduce extra css to fix some issues.

For instance what if we have a card or 2 with landscape images and one with portrait
how will the portrait image adjust in size so that it looks like it can be alongside the landscape variants?
![cards-with-different-images](https://user-images.githubusercontent.com/152852/152366125-1ab5373c-4dd2-409e-838a-f39d235e8ee2.png)
