### ISSUE TITLE
Segment Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#15]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-segment--default

- [x] Follow the  general guidelines given [here](https://github.com/eea/volto-eea-design-system/issues/48A)
- [x] Add  more content to the demo, different HTML tags of various sizes so that we can see
  how the container children behave when we have different viewport resolutions
- [x] Avoid eea variants in CSS, instead of overriding secondary simply change [variables](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/segment.less#L728)

**Comment by g-stamatis** [comment]
More variants have been added as ToDo in #107
