### ISSUE TITLE
Progress Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#28]
Component Demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-progress--default

- [x] Assign colors variables within site.variables and reference them here:
  https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/modules/progress.variables#L68
- [x] Same with background color, try to avoid custom values set on components only, it should be part of the site color pallet

## Mar 14 feedback
- [ ] Progress Percentage text fails accessibility

**Comment by g-stamatis** [comment]
Color codes are swapped with variables in the next push.
