### ISSUE TITLE
Pagination Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#35]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-pagination--default

- [x] Remove eea class style pagination menu directly using variables where possible, moving CSS out of menu.overrides
- [ ] Add more variants to storybook
- [ ] I much prefer the design found at React Semantic UI Pagination [ShortHand](https://react.semantic-ui.com/addons/pagination/#usage-shorthand).
  The go-to first and go to last is a lot more visible, the text is larger, everything seems more accessible than the
  current version even if it comes Semantic UI default style

**Comment by tiberiuichim** [comment]
@ichim-david About the variants, what type of variations do you miss? What do you have in mind?

As there's no custom component, only styling, there's no feedback needed on the React component.

**Comment by ichim-david** [comment]
@tiberiuichim  https://react.semantic-ui.com/addons/pagination/#usage-shorthand
There is the design from the shorthand version which looks like a better fit to me
then the current smaller design, especially on mobile devices.

**Comment by tiberiuichim** [comment]
Responsivity issues and more enhancements to be handled by ITML @g-stamatis

**Comment by g-stamatis** [comment]
ShortHand is not compliant with the design.

**Comment by g-stamatis** [comment]
More variants have been added as ToDo in #107
