### ISSUE TITLE
Pullquotes Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#39]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-pullquote--default

This component follows the same issues that I've detailed in the[ Blockquotes component](https://github.com/eea/volto-eea-design-system/issues/38)

Therefore I am keeping it short with examples and links, see the above ticket if extra details are needed

- [x] Follow Semantic UI conventions / constructs even for new components but use .eea parent class
- [x] Since it's a new component you need to define variables that can be set per component variable

**Comment by ichim-david** [comment]
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/menu.less#L135
https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/menu.less#L281

https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/extras/pullquote.less#L37
For classes where we have the name **right** or **left** you are not required to use a variable for the float
rule, only for situations where an element could have a display rule and a float where the user could choose
to set display to flex perhaps and float to none or left or right

**Comment by g-stamatis** [comment]
Component is to be redesigned in R3.
