### ISSUE TITLE
Page Banner (Header) Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#41]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-page-header--default

- [ ] use Semantic ui grid instead of the boostrap grid
- [ ] put content within a ui container for the title area and the side area with params so that
  they can be filled with anything
- [ ] use Semantic ui class naming
- [ ] remove styles from overrides move them to page-header.less
- [ ] use rem values for font size and bump them up, on mobile the meta was 7px, there
  is no way that is visible

More to follow after lunch break

**Comment by tiberiuichim** [comment]
See #61

**Comment by nileshgulia1** [comment]
TODO: Looks like we have different implementations in [theme](https://github.com/eea/volto-eea-website-theme/blob/develop/src/components/theme/Banner/Banner.jsx#L74) and [design system component](https://github.com/eea/volto-eea-design-system/blob/develop/src/ui/Banner/Banner.jsx#L10). Will try to create a sync PR.
