### ISSUE TITLE
Inpage Navigation Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#43]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-inpage-navigation--default

- [x]  Mouse cursor is text instead of hand
- [x] Once you reach top, the component should be hidden until you scroll again at least 200px
- [ ] On desktop I don't think "Top" text should be visible, since we have a multilingual site
  the button would be huge in many of those languages. 
  Instead opt to use "Go to top" as title to show only when hovering instead of having it always present.
- [ ] The button should be placed toward the lower bottom edge of the page, right now it's too
  close to the content area overlapping page content
- [x] Use container visibility classes for hiding elements at certain breakpoints
  ex: https://github.com/eea/volto-eea-design-system/blob/e7b5828c2f186f710546e6d106330b3b244ba903/theme/themes/eea/elements/container.overrides#L18
 Will hide that content on mobile resolutions, try to use these utility classes instead of adding extra media queries
 to show or hide content

**Comment by tiberiuichim** [comment]
Mouse cursor is text. Clicking on "scroll to top" button does nothing.

**Comment by g-stamatis** [comment]
The two open issues will be addressed in R3 redesign of this component.
