### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#45]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/layout-footer--default

- [x] Use Semantic ui grid, it also has mobile, tablet and desktop resolutions
 ex: https://codesandbox.io/s/djqif?module=/example.js
- [x] Have a look at Item and Card examples, perhaps you could get rid of the grid need altogether
   ex: https://codesandbox.io/s/semantic-ui-example-forked-mk0km?file=/example.js
   EDIT: in the end the solution was to use the semantic ui grid, for future we might change to semantic ui constructs
- [x] The usual Semantic ui naming and advice give in previous tickets

### Feb 24 Feedback

- [x] Use `anchor` tags for Footer sites.
- [x] Refactor and split Footer subcomponents on its own files in form of Footer.Actions, Footer.Sites:
Eg: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Modal/Modal.js#L23

### Mar 10 Feedback 
- [ ] Update  footer background image with latest design changes from figma
- [ ] Rename **visual** to **wrapper**

### Future fixes
- implement footer logos collapsing in mobile resolutions
- reduce selector complexity by avoiding deep nesting, keep a maximum of 3 selectors at all times instead of 6 in certain cases

**Comment by nileshgulia1** [comment]
### Feb 24 Feedback
- [ ] Use `anchor` tags for Footer sites.
- [ ] Refactor and split Footer subcomponents on its own files in form of Footer.Actions, Footer.Sites:
Eg: https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Modal/Modal.js#L23
