### ISSUE TITLE
H6 missing in site.variables

### ISSUE THREAD

**Issue by demarant** [eea/volto-eea-design-system#50]
H6 is present in typography documentation but [missing in code](https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/globals/site.variables#L75). Proposal: we could remove h6 from documentation, because h1-h5 is more than enough.
If we still want to have h6, than it cannot be smaller than the standard paragraph fontsize.

**Comment by ichim-david** [comment]
Fixed in latest commits
