### ISSUE TITLE
create principles/conventions and guidelines docs for developers

### ISSUE THREAD

**Issue by demarant** [eea/volto-eea-design-system#54]
In order to facilitate our design system develoment work, definition of done and QA of deliveries,
we need to create principles/conventions and guidelines section to be added in the github repo under /docs. 
Similar to what EC library has done here https://github.com/ec-europa/europa-component-library/tree/v3-dev/docs.

Our principles and guidlines should inherit everything that can be re-used from EC library and add what is specific for us to be conforman to SemanticUI framework
https://react.semantic-ui.com/
https://semantic-ui.com/usage/theming.html

- [ ] [Core principles](https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/core-principles.md) - All
- [ ] [Accessibility](https://github.com/ec-europa/europa-component-library/blob/v3-dev/docs/accessibility.md) - All
- [ ] CSS conventions and principles - Dos and Dont's - David.
- [ ] React conventions and principles - Dos and Dont's - Tiberiu
- [ ] Adding a new component - get started - David+Tiberiu

**Comment by tiberiuichim** [comment]
I've drafted React conventions here: https://gist.github.com/tiberiuichim/48707aea1d09aa88aac355a7ac1e4baa
